/* empty css                      */import{a as f,S as b,i as n}from"./assets/vendor-COEJfE63.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const w="54673230-281fb694487da15dcd571070d",v="https://pixabay.com/api/";f.defaults.baseURL=v;async function m(s,r=1){return(await f.get("",{params:{key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const p=document.querySelector(".gallery"),y=document.querySelector(".loader-text"),q=new b(".gallery a",{captionsData:"alt",captionDelay:250});function h(s){const r=s.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
          <p><b>Likes</b>${e.likes}</p>
          <p><b>Views</b>${e.views}</p>
          <p><b>Comments</b>${e.comments}</p>
          <p><b>Downloads</b>${e.downloads}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",r),q.refresh()}function S(){p.innerHTML=""}function g(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}const x=document.querySelector(".form"),a=document.querySelector(".load-more");let l="",i=1,d=0;x.addEventListener("submit",async s=>{s.preventDefault();const r=s.currentTarget.elements["search-text"].value.trim();if(!r){n.warning({message:"Please enter a search query!",position:"bottomCenter"});return}l=r,i=1,S(),a.classList.add("hidden"),g();try{const e=await m(l,i);if(d=e.totalHits,e.hits.length===0){n.info({message:"We're sorry, we couldn't find any images.",position:"bottomCenter"});return}h(e.hits),d>15&&a.classList.remove("hidden")}catch{n.error({message:"Error fetching images.",position:"bottomCenter"})}finally{L()}});a.addEventListener("click",async()=>{i+=1,g(),a.classList.add("hidden");try{const s=await m(l,i);h(s.hits),i*15>=d?(n.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}),a.classList.add("hidden")):a.classList.remove("hidden")}catch{n.error({message:"Error loading more images.",position:"bottomCenter"})}finally{L()}});
//# sourceMappingURL=index.js.map
