/* empty css                      */import{a as m,S as v,i as n}from"./assets/vendor-COEJfE63.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))f(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&f(a)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function f(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const S="54673230-281fb694487da15dcd571070d",q="https://pixabay.com/api/";m.defaults.baseURL=q;async function p(o,r=1){return(await m.get("",{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const u=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),C=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const r=o.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
          <p><b>Likes</b>${e.likes}</p>
          <p><b>Views</b>${e.views}</p>
          <p><b>Comments</b>${e.comments}</p>
          <p><b>Downloads</b>${e.downloads}</p>
        </div>
      </li>
    `).join("");u.insertAdjacentHTML("beforeend",r),C.refresh()}function E(){u.innerHTML=""}function b(){h.classList.add("is-visible")}function L(){h.classList.remove("is-visible")}function $(){const{height:o}=u.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}function w(){y.classList.remove("hidden")}function c(){y.classList.add("hidden")}const M=document.querySelector(".form"),P=document.querySelector(".load-more");let l="",i=1,d=0;M.addEventListener("submit",async o=>{o.preventDefault();const r=o.currentTarget.elements["search-text"].value.trim();if(!r){n.warning({message:"Please enter a search query!",position:"bottomCenter"});return}l=r,i=1,E(),c(),b();try{const e=await p(l,i);if(d=e.totalHits,e.hits.length===0){n.info({message:"We're sorry, we couldn't find any images.",position:"bottomCenter"});return}g(e.hits),d>15?w():n.info({message:"You've reached the end of search results.",position:"bottomCenter"})}catch{n.error({message:"Error fetching images.",position:"bottomCenter"})}finally{L()}});P.addEventListener("click",async()=>{i+=1,b(),c();try{const o=await p(l,i);g(o.hits),$(),i*15>=d?(n.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}),c()):w()}catch{n.error({message:"Error loading more images.",position:"bottomCenter"})}finally{L()}});
//# sourceMappingURL=index.js.map
